In [1]:
# importing the necessary packages 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# impoting the train.csv ( i will still split the dataset in to train and test for the analysis)
accident = pd.read_csv("train.csv")

accident = accident.drop(columns="id")
#displaying the first 5 observations of the dataset
accident.head()

,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk
0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13
1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35
2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30
3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21
4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56

In [3]:
# checking the type of data in the variables 
accident.dtypes

road_type                  object
num_lanes                   int64
curvature                 float64
speed_limit                 int64
lighting                   object
weather                    object
road_signs_present           bool
public_road                  bool
time_of_day                object
holiday                      bool
school_season                bool
num_reported_accidents      int64
accident_risk             float64
dtype: object

In [4]:
# checking the shape of the dataset
accident.shape

(517754, 13)

In [5]:
# checking the accident risk variable 
maximum_accident_risk = accident["accident_risk"].max()
minimum_accident_risk = accident["accident_risk"].min()

print(f"The minimum accident risk prob is {minimum_accident_risk} and the maximum accident risk prob is {maximum_accident_risk}")

The minimum accident risk prob is 0.0 and the maximum accident risk prob is 1.0

In [6]:
# checkig for missing figures in the dataset
accident.isna().any(axis=0).sum()

np.int64(0)

In [10]:
# converting number of reported accidents into binary 0 and 1 by mapping 
accident['is_accident'] = pd.Series(np.where(accident['num_reported_accidents'] >0, 1, 0), index=accident.index)

# checking my dataset to see if it is well
accident.head()

,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk,is_accident
0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13,1
1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35,0
2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30,1
3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21,1
4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56,1

In [11]:
accident.dtypes

road_type                  object
num_lanes                   int64
curvature                 float64
speed_limit                 int64
lighting                   object
weather                    object
road_signs_present           bool
public_road                  bool
time_of_day                object
holiday                      bool
school_season                bool
num_reported_accidents      int64
accident_risk             float64
is_accident                 int64
dtype: object